from __future__ import annotations
from ..widgets import FieldSpec as F

def catalog():
    return {
    'tasks': ('page.tasks','Gestiona subtareas, prioridad, recurrencia, progreso y vencimientos.','Manage subtasks, priority, recurrence, progress and deadlines.','tasks',['title','category','priority','status','due_date','progress'],[
        F('title','Título','Title',required=True),F('description','Descripción','Description','multiline'),F('category','Categoría','Category'),F('tags','Etiquetas','Tags'),F('priority','Prioridad','Priority','combo',('Low','Normal','High','Urgent'),default='Normal'),F('status','Estado','Status','combo',('pending','in_progress','waiting','done'),default='pending'),F('start_date','Fecha inicial','Start date','date'),F('due_date','Fecha límite','Due date','date'),F('reminder_at','Recordatorio','Reminder'),F('recurrence','Recurrencia','Recurrence','combo',('none','daily','weekly','monthly','yearly'),default='none'),F('estimated_minutes','Tiempo estimado (min)','Estimated time (min)','int'),F('progress','Progreso %','Progress %','int')],'due_date ASC,id DESC'),
    'alarms': ('page.alarms','Recordatorios locales con repetición real mientras AuraAgenda está activa.','Local reminders with real recurrence while AuraAgenda is running.','alarms',['alarm_date','alarm_time','name','repeat_rule','enabled','completed'],[F('name','Nombre','Name',required=True),F('alarm_date','Fecha','Date','date',required=True),F('alarm_time','Hora','Time','time',required=True),F('repeat_rule','Repetición','Repeat','combo',('once','daily','weekly','monthly'),default='once'),F('message','Mensaje','Message','multiline'),F('enabled','Activa','Active','combo',('Yes','No'),default='Yes'),F('completed','Completada','Completed','combo',('No','Yes'),default='No')],'alarm_date ASC,alarm_time ASC'),
    'habits': ('page.habits','Hábitos recurrentes con objetivo, días, color e icono.','Recurring habits with target, days, color and icon.','habits',['name','frequency','days','target','unit','active'],[F('name','Nombre','Name',required=True),F('frequency','Frecuencia','Frequency','combo',('daily','weekly','custom'),default='daily'),F('days','Días','Days'),F('target','Objetivo','Target','double',default='1'),F('unit','Unidad','Unit'),F('color','Color','Color'),F('icon','Icono','Icon'),F('active','Activo','Active','bool',default='1')],'id DESC'),
    'lists': ('page.lists','Listas para compras, viajes, regalos, ideas y más.','Lists for shopping, travel, gifts, ideas and more.','lists',['name','list_type','updated_at'],[F('name','Nombre','Name',required=True),F('list_type','Tipo','Type','combo',('Compras','Supermercado','Viaje','Equipaje','Cumpleaños','Pendientes','Regalos','Ideas','Películas','Libros','Wishlist','Personalizada')),F('notes','Notas','Notes','multiline')],'id DESC'),
    'writing': ('page.writing','Espacio creativo para textos, cartas, poemas e ideas.','Creative space for texts, letters, poems and ideas.','writing',['kind','title','status','updated_at'],[F('kind','Tipo','Type','combo',('Poetry','Quote','Idea','Story','Moment','Song','Letter','Reflection','Free project')),F('title','Título','Title',required=True),F('body','Texto','Text','multiline'),F('status','Estado','Status','combo',('Draft','In development','Review','Finished'))],'updated_at DESC'),
    'people': ('page.people','Contactos, cumpleaños, regalos e interacciones importantes.','Contacts, birthdays, gifts and important interactions.','people',['name','relationship','birthday','phone','last_interaction'],[F('name','Nombre','Name',required=True),F('relationship','Relación','Relationship'),F('birthday','Cumpleaños','Birthday','date'),F('phone','Teléfono','Phone'),F('email','Email','Email'),F('address','Dirección','Address'),F('gift_ideas','Ideas de regalos','Gift ideas','multiline'),F('last_interaction','Última interacción','Last interaction','date'),F('notes','Notas','Notes','multiline')],'name ASC'),
    'goals': ('page.goals','Metas personales y profesionales con progreso y subtareas.','Personal and professional goals with progress and subtasks.','goals',['title','category','target_date','progress','status'],[F('title','Título','Title',required=True),F('category','Categoría','Category','combo',('Personal','Profesional','Dinero','Salud','Estudios','Viajes','Bienestar','Otros')),F('start_date','Fecha inicial','Start date','date'),F('target_date','Fecha objetivo','Target date','date'),F('progress','Progreso %','Progress %','int'),F('subtasks','Subtareas','Subtasks','multiline'),F('notes','Notas','Notes','multiline'),F('status','Estado','Status','combo',('active','paused','done'),default='active')],'target_date ASC'),
    'cycle': ('page.cycle','Registro opcional de ciclo y síntomas. Las predicciones son estimaciones de organización personal.','Optional cycle and symptom log. Predictions are personal organization estimates.','cycle_records',['start_date','end_date','duration_days','intensity','symptoms'],[F('start_date','Inicio','Start','date',required=True),F('end_date','Final','End','date'),F('duration_days','Duración (días)','Duration (days)','int'),F('intensity','Intensidad','Intensity','combo',('Low','Medium','High')),F('symptoms','Síntomas','Symptoms','multiline'),F('notes','Notas','Notes','multiline')],'start_date DESC'),
    'wellness': ('page.wellness','Registro personal opcional; no realiza diagnósticos ni recomendaciones médicas.','Optional personal log; it does not diagnose or provide medical recommendations.','wellness_logs',['log_date','pain','energy','mood','sleep','stress'],[F('log_date','Fecha','Date','date',required=True),F('pain','Dolor 0-10','Pain 0-10','int'),F('energy','Energía 0-10','Energy 0-10','int'),F('mood','Humor 0-10','Mood 0-10','int'),F('sleep','Sueño 0-10','Sleep 0-10','int'),F('stress','Estrés 0-10','Stress 0-10','int'),F('appetite','Apetito 0-10','Appetite 0-10','int'),F('skin','Piel','Skin'),F('migraine','Migraña 0-10','Migraine 0-10','int'),F('bloating','Hinchazón 0-10','Bloating 0-10','int'),F('custom_symptoms','Otros síntomas','Other symptoms'),F('notes','Notas','Notes','multiline')],'log_date DESC'),
    'sleep': ('page.sleep','Seguimiento opcional del sueño sin diagnóstico médico.','Optional sleep tracking without medical diagnosis.','sleep_logs',['sleep_date','bedtime','wake_time','hours','quality','interruptions'],[F('sleep_date','Fecha','Date','date',required=True),F('bedtime','Hora de dormir','Bedtime','time'),F('wake_time','Hora de despertar','Wake time','time'),F('hours','Horas','Hours','double'),F('quality','Calidad 0-10','Quality 0-10','int'),F('interruptions','Interrupciones','Interruptions','int'),F('comment','Comentario','Comment','multiline')],'sleep_date DESC'),
    'mood': ('page.mood','Emociones, intensidad, etiquetas y notas.','Emotions, intensity, tags and notes.','mood_logs',['recorded_at','emotion','intensity','tags'],[F('emotion','Emoción','Emotion',required=True),F('intensity','Intensidad 1-10','Intensity 1-10','int'),F('recorded_at','Fecha/hora','Date/time'),F('note','Nota','Note','multiline'),F('tags','Etiquetas','Tags')],'recorded_at DESC'),
    'selfcare': ('page.selfcare','Rutinas de skincare, cabello, ejercicio, descanso y tiempo personal.','Skincare, hair, exercise, rest and personal-time routines.','selfcare',['scheduled_date','activity','category','frequency','completed'],[F('activity','Actividad','Activity',required=True),F('category','Categoría','Category','combo',('Skincare AM','Skincare PM','Cabello','Uñas','Tratamientos','Spa','Ejercicio','Descanso','Meditación','Lectura','Tiempo personal')),F('frequency','Frecuencia','Frequency'),F('scheduled_date','Fecha','Date','date'),F('completed','Completado','Completed','bool'),F('notes','Notas','Notes','multiline')],'scheduled_date DESC'),
    'beauty': ('page.beauty','Productos, vencimientos, wishlist y recompra.','Products, expiry dates, wishlist and repurchase.','beauty_products',['name','brand','category','expiry_date','rating','status'],[F('name','Nombre','Name',required=True),F('brand','Marca','Brand'),F('category','Categoría','Category'),F('price','Precio','Price','double'),F('currency','Moneda','Currency'),F('purchase_date','Fecha de compra','Purchase date','date'),F('open_date','Fecha de apertura','Open date','date'),F('expiry_date','Vencimiento','Expiry date','date'),F('rating','Valoración 0-10','Rating 0-10','int'),F('notes','Notas','Notes','multiline'),F('photo','Foto','Photo'),F('repurchase','Repetir compra','Repurchase','combo',('No','Yes')),F('status','Estado','Status','combo',('active','wishlist','finish_soon','finished'))],'id DESC'),
    'style': ('page.style','Guardar prendas, colores, estaciones y ocasiones.','Save garments, colors, seasons and occasions.','wardrobe',['name','category','color','season','occasion','brand','favorite'],[F('name','Prenda','Item',required=True),F('category','Categoría','Category'),F('color','Color','Color'),F('season','Estación','Season'),F('occasion','Ocasión','Occasion','combo',('Trabajo','Casual','Fiesta','Cena','Viaje','Gym','Invierno','Verano')),F('brand','Marca','Brand'),F('photo','Foto','Photo'),F('notes','Notas','Notes','multiline'),F('favorite','Favorito','Favorite','bool')],'id DESC'),
    'finance': ('page.finance','Ingresos, gastos, métodos de pago y vencimientos en la moneda que elijas.','Income, expenses, payment methods and due dates in your chosen currency.','finance',['txn_date','txn_type','category','concept','amount','currency','status'],[F('txn_date','Fecha','Date','date',required=True),F('txn_type','Tipo','Type','combo',('income','expense'),required=True),F('category','Categoría','Category'),F('concept','Concepto','Concept',required=True),F('amount','Importe','Amount','double',required=True),F('currency','Moneda','Currency'),F('status','Estado','Status','combo',('paid','pending')),F('payment_method','Método de pago','Payment method'),F('recurring','Recurrente','Recurring','combo',('No','Yes')),F('due_date','Vencimiento','Due date','date'),F('note','Nota','Note','multiline')],'txn_date DESC'),
    'travel': ('page.travel','Planifica destinos, reservas, presupuesto, documentos y outfits.','Plan destinations, reservations, budget, documents and outfits.','trips',['destination','start_date','end_date','budget','currency'],[F('destination','Destino','Destination',required=True),F('start_date','Inicio','Start','date'),F('end_date','Final','End','date'),F('accommodation','Alojamiento','Accommodation'),F('transport','Transporte','Transport'),F('reservations','Reservas','Reservations','multiline'),F('budget','Presupuesto','Budget','double'),F('currency','Moneda','Currency'),F('checklist','Checklist','Checklist','multiline'),F('documents','Documentos','Documents','multiline'),F('places','Lugares','Places','multiline'),F('outfits','Outfits','Outfits','multiline'),F('reminders','Recordatorios','Reminders','multiline'),F('notes','Notas','Notes','multiline')],'start_date DESC'),
    'library': ('page.library','Documentos, fotos, videos, audios y enlaces por referencia o copia local.','Documents, photos, videos, audio and links by reference or local copy.','library',['title','file_type','category','storage_mode','favorite','path'],[F('title','Título','Title',required=True),F('file_type','Tipo','Type'),F('path','Ruta','Path',required=True),F('storage_mode','Modo','Storage mode','combo',('reference','local_copy')),F('category','Categoría','Category'),F('tags','Etiquetas','Tags'),F('favorite','Favorito','Favorite','bool')],'id DESC'),
    'multimedia': ('page.multimedia','Covers, canciones, videos, audios, portadas, letras y proyectos.','Covers, songs, videos, audio, artwork, lyrics and projects.','multimedia',['title','media_type','artist','song','status','path'],[F('title','Título','Title',required=True),F('media_type','Tipo','Type','combo',('Cover','Song','Video','Audio','Artwork','Lyrics','Project')),F('artist','Artista','Artist'),F('song','Canción','Song'),F('path','Ruta','Path'),F('storage_mode','Modo','Storage mode','combo',('reference','local_copy')),F('status','Estado','Status'),F('tags','Etiquetas','Tags')],'id DESC'),
    }
